### ISSUE TITLE
Extend ROSCORE over the wireless network

### ISSUE THREAD

**Issue by correll** [correll/advancedrobotics#11]
Demonstrate
-remote control
-video feed

**Comment by Athithyaa** [comment]
I am looking at the basics for ROS. Will take this issue up and try to come up with a solution

**Comment by correll** [comment]
That's great! The Jetson does not have wireless yet. Let's find a mini PCIe card that has an antenna connector that matches the cable already in the Jaguar or use the white wireless access point.

In the long run we want to have two networking devices to debug that thing, so using the wap on the Ethernet port is not optimal.
