### ISSUE TITLE
Install drivers for OccamVision cameras

### ISSUE THREAD

**Issue by correll** [correll/advancedrobotics#13]
Drivers for Ubuntu 14.04 / ROS Indigo are available from OccamRobotic's website

**Comment by mira67** [comment]
Downloaded "ros_indigosdk-2.0.0.tar" and followed the instructions from readme.txt
Tried install the package on Ubutun 14.04 with ROS, got the following error from cmake error log:
/usr/bin/ld: cannot find -lpthread
Anyone has come across same issue?
(Could be the configuration of my ubutun, will test the installation on Jetson.)

**Comment by ghost** [comment]
-lpthread is an external library which is used to create threads in Ubuntu.
Commonly used along with c/c++ threaded programs. Usually it comes
preinstalled with Ubuntu or along with the gcc compiler. It seems you don't
have that library. Try installing the gcc compiler (which will most
probably contain the lpthread library) or try intalling it separately using
Ububtu Software center.

Regards,
Rohit

**Comment by Athithyaa** [comment]
Yes, did you try updating the source.list file to get updated packages list
for ROS ?.

Installing ROS Indigo on Ubuntu 14.0.4.X was smooth sailing for me.

Try this http://wiki.ros.org/indigo/Installation/Ubuntu. It has clear cut
info.

Thanks,
Athithyaa

On Sun, Aug 30, 2015 at 10:33 PM, Rohit Narendra Raje <
notifications@github.com> wrote:

> -lpthread is an external library which is used to create threads in Ubuntu.
> Commonly used along with c/c++ threaded programs. Usually it comes
> preinstalled with Ubuntu or along with the gcc compiler. It seems you don't
> have that library. Try installing the gcc compiler (which will most
> probably contain the lpthread library) or try intalling it separately using
> Ububtu Software center.
> 
> Regards,
> Rohit
> 
> On Sunday, August 30, 2015, mira67 notifications@github.com wrote:
> 
> > Downloaded "ros_indigosdk-2.0.0.tar" and followed the instructions from
> > readme.txt
> > Tried install the package on Ubutun 14.04 with ROS, got the following
> > error from cmake error log:
> > /usr/bin/ld: cannot find -lpthread
> > Anyone has come across same issue?
> > (Could be the configuration of my ubutun, will test the installation on
> > Jetson.)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/correll/advancedrobotics/issues/13#issuecomment-136247029
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/correll/advancedrobotics/issues/13#issuecomment-136249715
> .

## 

Thanks and Regards,
Athithyaa PR

**Comment by mira67** [comment]
ROS installation has no issue.
The installation of package for omni 60 has errors. Will troubleshoot
tomorrow.
Thanks.

On Sun, Aug 30, 2015 at 11:40 PM, Athithyaa notifications@github.com
wrote:

> Yes, did you try updating the source.list file to get updated packages list
> for ROS ?.
> 
> Installing ROS Indigo on Ubuntu 14.0.4.X was smooth sailing for me.
> 
> Try this http://wiki.ros.org/indigo/Installation/Ubuntu. It has clear cut
> info.
> 
> Thanks,
> Athithyaa
> 
> On Sun, Aug 30, 2015 at 10:33 PM, Rohit Narendra Raje <
> notifications@github.com> wrote:
> 
> > -lpthread is an external library which is used to create threads in
> > Ubuntu.
> > Commonly used along with c/c++ threaded programs. Usually it comes
> > preinstalled with Ubuntu or along with the gcc compiler. It seems you
> > don't
> > have that library. Try installing the gcc compiler (which will most
> > probably contain the lpthread library) or try intalling it separately
> > using
> > Ububtu Software center.
> > 
> > Regards,
> > Rohit
> > 
> > On Sunday, August 30, 2015, mira67 notifications@github.com wrote:
> > 
> > > Downloaded "ros_indigosdk-2.0.0.tar" and followed the instructions from
> > > readme.txt
> > > Tried install the package on Ubutun 14.04 with ROS, got the following
> > > error from cmake error log:
> > > /usr/bin/ld: cannot find -lpthread
> > > Anyone has come across same issue?
> > > (Could be the configuration of my ubutun, will test the installation on
> > > Jetson.)
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/correll/advancedrobotics/issues/13#issuecomment-136247029
> > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/correll/advancedrobotics/issues/13#issuecomment-136249715
> > 
> > .
> 
> ## 
> 
> Thanks and Regards,
> Athithyaa PR
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/correll/advancedrobotics/issues/13#issuecomment-136271555
> .

## 

PhD Candidate
ECEE Department
University of Colorado at Boulder

**Comment by Athithyaa** [comment]
Sorry, my bad.... :(
understood your issue.

A.

On Sun, Aug 30, 2015 at 11:43 PM, mira67 notifications@github.com wrote:

> ROS installation has no issue.
> The installation of package for omni 60 has errors. Will troubleshoot
> tomorrow.
> Thanks.
> 
> On Sun, Aug 30, 2015 at 11:40 PM, Athithyaa notifications@github.com
> wrote:
> 
> > Yes, did you try updating the source.list file to get updated packages
> > list
> > for ROS ?.
> > 
> > Installing ROS Indigo on Ubuntu 14.0.4.X was smooth sailing for me.
> > 
> > Try this http://wiki.ros.org/indigo/Installation/Ubuntu. It has clear
> > cut
> > info.
> > 
> > Thanks,
> > Athithyaa
> > 
> > On Sun, Aug 30, 2015 at 10:33 PM, Rohit Narendra Raje <
> > notifications@github.com> wrote:
> > 
> > > -lpthread is an external library which is used to create threads in
> > > Ubuntu.
> > > Commonly used along with c/c++ threaded programs. Usually it comes
> > > preinstalled with Ubuntu or along with the gcc compiler. It seems you
> > > don't
> > > have that library. Try installing the gcc compiler (which will most
> > > probably contain the lpthread library) or try intalling it separately
> > > using
> > > Ububtu Software center.
> > > 
> > > Regards,
> > > Rohit
> > > 
> > > On Sunday, August 30, 2015, mira67 notifications@github.com wrote:
> > > 
> > > > Downloaded "ros_indigosdk-2.0.0.tar" and followed the instructions
> > > > from
> > > > readme.txt
> > > > Tried install the package on Ubutun 14.04 with ROS, got the following
> > > > error from cmake error log:
> > > > /usr/bin/ld: cannot find -lpthread
> > > > Anyone has come across same issue?
> > > > (Could be the configuration of my ubutun, will test the installation
> > > > on
> > > > Jetson.)
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/correll/advancedrobotics/issues/13#issuecomment-136247029
> > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/correll/advancedrobotics/issues/13#issuecomment-136249715
> > 
> > > .
> > 
> > ## 
> > 
> > Thanks and Regards,
> > Athithyaa PR
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/correll/advancedrobotics/issues/13#issuecomment-136271555
> > 
> > .
> 
> ## 
> 
> PhD Candidate
> ECEE Department
> University of Colorado at Boulder
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/correll/advancedrobotics/issues/13#issuecomment-136272520
> .

## 

Thanks and Regards,
Athithyaa PR

**Comment by ryanleonard** [comment]
Hey everyone, 
So Regina and I are working on installing some things for the Tegra, but we aren't sure exactly where you guys left off. 

Can you confirm that ROS has/hasn't been installed?

We ask this because as far as we can tell, -lpthread has not yet been installed...

For future reference, we are leaving a text file under Documents on the tegra itself to let everyone else know what we have done so that if any problems arise in the future we can have some documentation which may help to resolve the issue.

**Comment by mira67** [comment]
The driver package for omni60 was downloaded to jetson and under /Download folder.

installed image-transport, image-info-manager for ROS to support the camera
installed usblib which was missing
The same issue metioned previously occured when installing package for omni60 on jetson

If any of you have more experience on installing 3rd party package for ROS, the instructions for installing omni60 is in the readme file in the driver directory /Downloads/ros-indigosdk-2.0.0, you can help check the issue. Meanwhile, I am researching the solutions.

**Comment by mira67** [comment]
Resolved the non-supported msse2 option issue.
But after that, new errors coming up due to the flaw of occam sdk source code
Occam custom support gave a potential solution and they will examine the source code
Will take some time to resolve this issue, but on track.

**Comment by mira67** [comment]
Thanks to someone who helped fixed the problem.
"ARM_NEON" flag has to be defined to make thing work smoothly. 
Now the camera sdk/driver was installed and linked with ROS. DONE!
(Going to create another issue to track "UDEV RULE" for the Camera)

**Comment by rmaheshkumarblr** [comment]
Can you please provide instructions on how to start the Occam camera on the wiki?

**Comment by mira67** [comment]
ok, will document that tomorrow

On Thu, Sep 17, 2015 at 6:17 PM, Mahesh Kumar Ravindranathan <
notifications@github.com> wrote:

> Can you please provide instructions on how to start the Occam camera on
> the wiki?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/correll/advancedrobotics/issues/13#issuecomment-141293150
> .

## 

PhD Candidate
ECEE Department
University of Colorado at Boulder
