### ISSUE TITLE
Install OpenCV for Tegra

### ISSUE THREAD

**Issue by correll** [correll/advancedrobotics#15]

**Comment by rmaheshkumarblr** [comment]
This link provides how to go about installing OpenCV for Tegra: http://elinux.org/Jetson/Installing_OpenCV
Will try it in the lab on Monday or Tuesday

**Comment by correll** [comment]
That's good. Need to coordinate with whoever flashes the Jetson with LT4 21.x (Rohit?).

I recommend to go the route of using the precompiled option (optimized for tegra) and add support for sift/surf manually at a later point.

https://en.m.wikipedia.org/wiki/Speeded_up_robust_features

**Comment by ghost** [comment]
Yea. I'll be doing the Jetson Flashing on Monday. We will do the OpenCV
together.

Regards,
Rohit

**Comment by rmaheshkumarblr** [comment]
Hi Rohit, 

I am in the Lab, let me know when you would be available. I don't have your number yet so I thought will use Github instead for the time being..

**Comment by ikemole** [comment]
I have installed CUDA. According to the instructions link above, it is required to install CUDA on the Jetson before you can install OpenCV, so now you can go ahead and install OpenCV.

**Comment by ghost** [comment]
I have install OpenCV. Issue Closed!

**Comment by ghost** [comment]
I have installed the native-compiled OpenCV which has full functionality including GPU support.
Common way of running c++ programs in openCV is (running a sample program called edge.cpp, dont forget to include --cflags and --libs from opencv):
cd opencv-3.0.0/samples/cpp/
g++ edge.cpp -o edge $(pkg-config opencv --cflags --libs)
./edge
