### ISSUE TITLE
Collect a list of BuffId + Names to obtain lab access

### ISSUE THREAD

**Issue by correll** [correll/advancedrobotics#16]

**Comment by ghost** [comment]
To @ryanleonard 
Do you have the existing list of BuffId + Names so that I can update it for access to the Correll lab?

**Comment by rmaheshkumarblr** [comment]
There are no 80-20's in the lab and I have no access to Correll lab, so Zach could not get the hardware fixed.

In case you are collecting the name and buffid list again. Here are the details.

Name: Mahesh Kumar Ravindranathan
BuffID: 6014235005240075

**Comment by correll** [comment]
Radhen was in the lab earlier. Shall I come in and open the door?

On Sat, Oct 24, 2015 at 1:38 PM, Mahesh Kumar Ravindranathan <
notifications@github.com> wrote:

> There are no 80-20's in the lab and I have no access to Correll lab, so
> Zach could not get the hardware fixed.
> 
> In case you are collecting the name and buffid list again. Here are the
> details.
> 
> Name: Mahesh Kumar Ravindranathan
> BuffID: 6014235005240075
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/correll/advancedrobotics/issues/16#issuecomment-150842984
> .

## 

Assistant Professor
@correlllab, http://correll.cs.colorado.edu
Open robotics textbook: http://amzn.to/1vTjnt9 (buy), http://bit.ly/1vr7ptA
(contribute)

**Comment by rmaheshkumarblr** [comment]
Rohit is on his way to the college, he has access. He must be able to open the door.

**Comment by ryanleonard** [comment]
If you guys still have trouble getting in for whatever reason, just give me a call. 
720-339-6304
Also, Steve found a bag of some 80x20 stuff which is up against the wall by the jag. I have no idea whats in there though...

Date: Sat, 24 Oct 2015 12:42:10 -0700

**Comment by jilu7883** [comment]
I am in the engineering center right now, I can open the door

**Comment by rmaheshkumarblr** [comment]
@RohitRaje9362 opened the door.

**Comment by ghost** [comment]
I already did.

Rohit

**Comment by jilu7883** [comment]
OK
