### ISSUE TITLE
Install wireless mini PCIe card (need to be ordered)

### ISSUE THREAD

**Issue by correll** [correll/advancedrobotics#17]
There is a SMA (?) cable wiring an antenna to the outside. Need to make sure the PCI card supports external antenna.

**Comment by correll** [comment]
There is a SMA (?) cable wiring an antenna to the outside. Need to make sure the PCI card supports external antenna.

**Comment by rmaheshkumarblr** [comment]
The following link shows the PCI cards that are supported via the Grinch Kernal 

http://elinux.org/Jetson/Network_Adapters

The ones which we have are different from the supported list. Will try to use them anyways to check if they are detectable.

One of them we have is Intel Centrino 2230 which Nvidia plans to support in future for the Tegra platform. Reference from the link provided above.

**Comment by correll** [comment]
If you find one on Amazon, I can buy it. Make sure it has a connector for the external antenna!

**Comment by rmaheshkumarblr** [comment]
The recommended one for Jetson using the grinch kernal is Intel : 7260 HMW

Instruction on how to install and use: http://jetsonhacks.com/2014/10/12/installing-wireless-intel-7260-adapter-nvidia-jetson-tk1/

Amazon link for the module: http://www.amazon.com/gp/product/B00DMCVKMU/ ( It can have two external antennas attached to it )
Amazon link if antennas are required: http://www.amazon.com/Mini-Antenna-RP-SMA-Bulkhead-Pigtail/dp/B007XVHQ9M/

**Comment by correll** [comment]
I'd be glad to order, but do we need the antenna or can use that already in the jaguar?

**Comment by rmaheshkumarblr** [comment]
I think Jaquar came with just one antenna. We could use one of those and buy one more since this wireless module has slot for two external antennas.

**Comment by correll** [comment]
I have ordered the module and antenna

On Sat, Sep 5, 2015 at 9:51 AM, Mahesh Kumar Ravindranathan <
notifications@github.com> wrote:

> I think Jaquar came with just one antenna. We could use one of those and
> buy one more since this wireless module has slot for two external antennas.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/correll/advancedrobotics/issues/17#issuecomment-137970264
> .

## 

Assistant Professor
@correlllab, http://correll.cs.colorado.edu
Open robotics textbook: http://amzn.to/1vTjnt9 (buy), http://bit.ly/1vr7ptA
(contribute)

**Comment by rmaheshkumarblr** [comment]
We just fixed the wireless module and it started working. Looks like it got the drivers from the grinch kernel.
