### ISSUE TITLE
Installing ROS drivers to drive motors

### ISSUE THREAD

**Issue by correll** [correll/advancedrobotics#2]

**Comment by ghost** [comment]
I'll start installing the ROS drivers which Steve has written, after I flash the Jettson and install ROS. Does anyone want to join me? I will be starting this on Monday from 11:30am. 

Regards,
Rohit

**Comment by rmaheshkumarblr** [comment]
I will join you. Would like to know how flashing is done onto the Jetson.

Thanks and Regards,
Mahesh Kumar

**Comment by Athithyaa** [comment]
Rohit, Yes I can join you. Meet you on Monday at 1130.

A.

**Comment by ghost** [comment]
Cool. I will be starting tomorrow at 11:30am. You can join in as you become
free.

Rohit

**Comment by mcguire-steve** [comment]
ROS code updated, traced to use of static initializers. Replaced with dynamic. Tested, able to drive the Jaguar via joystick. Pull code to update.
