### ISSUE TITLE
Implement FTDI management in Linux

### ISSUE THREAD

**Issue by correll** [correll/advancedrobotics#20]
FTDI devices are labeled as /dev/ttyUSBx. We will need to provide fixed names (via the devices serial numbers) in order to prevent confusion.

**Comment by rmaheshkumarblr** [comment]
ubuntu@tegra-ubuntu:~/catkin_ws/src/robot_localization/launch$ cat /etc/udev/rules.d/10-self-defined.rules  | head -2
SUBSYSTEM=="tty", ATTRS{idVendor}=="0403" , ATTRS{manufacturer}=="FTDI"  ,ATTRS{serial}=="AL00ITFV" ,  MODE="0666" , SYMLINK+="GPS_System"
SUBSYSTEM=="tty", ATTRS{idVendor}=="0403" , ATTRS{manufacturer}=="FTDI"  ,ATTRS{serial}=="AH02LWD6" ,  MODE="0666" , SYMLINK+="IMU_System"
ubuntu@tegra-ubuntu:~/catkin_ws/src/robot_localization/launch$ 

ubuntu@tegra-ubuntu:~/catkin_ws/src/robot_localization/launch$ ls -ltrh /dev/GPS_System /dev/IMU_System 
lrwxrwxrwx 1 root root 7 Sep 16 23:32 /dev/GPS_System -> ttyUSB0
lrwxrwxrwx 1 root root 7 Sep 16 23:32 /dev/IMU_System -> ttyUSB1
ubuntu@tegra-ubuntu:~/catkin_ws/src/robot_localization/launch$ 

Bus 001 Device 006: ID 0403:6001 Future Technology Devices International, Ltd FT232 USB-Serial (UART) IC
Bus 001 Device 005: ID 0403:6001 Future Technology Devices International, Ltd FT232 USB-Serial (UART) IC

**Comment by Jorge-C** [comment]
This can be closed, right?

**Comment by rmaheshkumarblr** [comment]
I think we will have to continue with updating the udev rules till all the hardwares are connected to ROS.
Right now only Occam Camera, GPS and IMU are updated. We could close this since the FTDI devices are updated but we could open one new issue for all devices in general ( DC Motors, IMU from stuart platform, etc.. )

**Comment by rmaheshkumarblr** [comment]
Updated the UDEV rules to include the USB module that connects to the Motor Controller.
Also modified an existing 3.3V FTDI module to work with IMU so that Motor Controller and IMU can work independently (Not sharing the same FTDI cable anymore)

```
/etc/udev/rules.d/10-self-defined.rules

SUBSYSTEM=="tty", ATTRS{idVendor}=="0403" , ATTRS{manufacturer}=="FTDI"  ,ATTRS{serial}=="AL00ITFV" ,  MODE="0666" , SYMLINK+="GPS_System"
SUBSYSTEM=="tty", ATTRS{idVendor}=="0403" , ATTRS{manufacturer}=="FTDI"  ,ATTRS{serial}=="A703EBFG" ,  MODE="0666" , SYMLINK+="IMU_System"
SUBSYSTEM=="tty", ATTRS{idVendor}=="0403" , ATTRS{manufacturer}=="FTDI"  ,ATTRS{serial}=="AH02LWD6" ,  MODE="0666" , SYMLINK+="MOTOR_System"
SUBSYSTEM=="usb", ATTRS{idVendor}=="285e" , ENV{ID_SERIAL_SHORT}=="811168f166914178", MODE="0666" , SYMLINK+="OccamCamera"
```

**Comment by rmaheshkumarblr** [comment]
Updated udev rules to detect joystick automatically.

Udev rules will  automatically change the baud rate of the motor control system to 115200 by default.

```
ubuntu@tegra-ubuntu:~/catkin_ws$ cat /etc/udev/rules.d/10-self-defined.rules
SUBSYSTEM=="tty", ATTRS{idVendor}=="0403" , ATTRS{manufacturer}=="FTDI"  ,ATTRS{serial}=="AL00ITFV" ,  MODE="0666" , SYMLINK+="GPS_System"
SUBSYSTEM=="tty", ATTRS{idVendor}=="0403" , ATTRS{manufacturer}=="FTDI"  ,ATTRS{serial}=="A703EBFG" ,  MODE="0666" , SYMLINK+="IMU_System"
SUBSYSTEM=="tty", ATTRS{idVendor}=="0403" , ATTRS{manufacturer}=="FTDI"  ,ATTRS{serial}=="AH02LWD6" ,  MODE="0666" , SYMLINK+="MOTOR_System" , RUN+="/bin/stty -F /dev/MOTOR_System 115200"
KERNEL=="js*" , SUBSYSTEM=="input", ATTRS{idVendor}=="046d" , ATTRS{manufacturer}=="Logitech" , ATTRS{serial}=="74469186" , MODE="0666" , SYMLINK+="JOYSTICK_System"
SUBSYSTEM=="usb", ATTRS{idVendor}=="285e" , ENV{ID_SERIAL_SHORT}=="811168f166914178", MODE="0666" , SYMLINK+="OccamCamera"
ubuntu@tegra-ubuntu:~/catkin_ws$ 

```

**Comment by Jorge-C** [comment]
The udev rules for the stewart platform components have also been integrated.
