### ISSUE TITLE
Determine presence and type of motor encoders

### ISSUE THREAD

**Issue by correll** [correll/advancedrobotics#30]

**Comment by rmaheshkumarblr** [comment]
Data sheet of the motor driver that is being used.

https://www.dimensionengineering.com/datasheets/Sabertooth2x25v2.pdf

Data sheet that contains the Encoders used in PMS5005.

http://www.drrobot.com/products/item_downloads/PMS5005_1.pdf

![image](https://cloud.githubusercontent.com/assets/1996917/10112587/96ecec1a-6399-11e5-84d7-282fbb967b4c.png)

<b>Quadrature encoder</b> is being used.

https://en.wikipedia.org/wiki/Rotary_encoder
http://www.ni.com/white-paper/4763/en/
