### ISSUE TITLE
Calibrate the IMU for the Stewart Platform

### ISSUE THREAD

**Issue by rcr2f** [correll/advancedrobotics#35]
Is someone familiar with calibrating the Sparkfun Razor 9DOF IMU already and want to take this on? 

https://github.com/ptrbrtz/razor-9dof-ahrs/wiki/Tutorial

**Comment by bryanbocao** [comment]
@Jorge-C and I have calibrated the IMU but outside the robot. But the magnetometer of the IMU needs to be calibrated again since it is affected by other metals and electronic components.

**Comment by Jorge-C** [comment]
Bryan, there's another IMU in the Stewart platform. That one needs to have the magnetometer calibrated (Andy calibrated accels and gyros already, but it'd still be good to calibrate them again).

**Comment by bryanbocao** [comment]
Below is the calibration config file for accelerometer and gyro.
[razor_stewart.yaml.txt](https://github.com/correll/advancedrobotics/files/18952/razor_stewart.yaml.txt)
Magnetometer could be calibrated when the IMU is attached to the steward platform.

Note that the extension .txt has to be removed.
Thank @Jorge-C and @RohitRaje9362 for help.
