### ISSUE TITLE
Gigabit ethernet cat 5e port on the Jaguar Platform

### ISSUE THREAD

**Issue by rcr2f** [correll/advancedrobotics#37]
Similar to the USB 3 port

**Comment by rcr2f** [comment]
LCOM

**Comment by ryanleonard** [comment]
http://www.amazon.com/Waterproof-CAT5e-RJ45-Feed-Thru-Coupler/dp/B00CULLAWE/ref=sr_1_fkmr0_2?ie=UTF8&qid=1443819958&sr=8-2-fkmr0&keywords=female+female+ethernet+weather+resistant

I think that this is going to be a pretty good option.

But we will also need a cover:
http://www.amazon.com/CAT5e-Case-Side-Waterproof-Tether/dp/B00CUM7RF2/ref=pd_bxgy_147_img_2?ie=UTF8&refRID=131JB5BC674Q58HMZS96

**Comment by mcguire-steve** [comment]
USB3: http://www2.usbfirewire.com/Parts/rr-118300-0s-xx.html#RR-118300-0S-12
with cover: http://www2.usbfirewire.com/Parts/rr-118300-0s-xx.html#RR-1C533122
