### ISSUE TITLE
Configure Costmap (local_costmap) & (global_costmap)

### ISSUE THREAD

**Issue by bryanbocao** [correll/advancedrobotics#49]
[RobotSetup 3.3 Costmap Configuration (local_costmap) & (global_costmap)](http://wiki.ros.org/navigation/Tutorials/RobotSetup)

[costmap_2d](http://wiki.ros.org/costmap_2d)

Sub-issue of #36

**Comment by Branden-Romero** [comment]
![map](https://cloud.githubusercontent.com/assets/5060579/11669985/b69c7f32-9dbc-11e5-87b2-e9be61d9f0f0.png)

Cost map of ECCR 1B15.

**Comment by correll** [comment]
Does this also work outside?

**Comment by Branden-Romero** [comment]
Will try when we get a new usb to serial breakout, can't drive now.

**Comment by correll** [comment]
We should have a couple in the lab still

**Comment by Branden-Romero** [comment]
By any chance do you know where?

**Comment by Jorge-C** [comment]
We already talked to Andy about it and could not find any. Is there any
place we should double check?

2015-12-08 17:18 GMT-07:00 Branden Romero notifications@github.com:

**Comment by correll** [comment]
John might know

**Comment by Branden-Romero** [comment]
![screenshot from 2015-12-09 19 13 47](https://cloud.githubusercontent.com/assets/5060579/11704915/1d2d12ce-9ea9-11e5-8820-03d4a9c325fa.png)
![img_20151209_131359](https://cloud.githubusercontent.com/assets/5060579/11704948/5d54bed8-9ea9-11e5-8925-37a7ed73fdc2.jpg)
Got better results for outdoor map. Scan match doesn't find a match consistently so there is ghosting on the trees on bottom right and left.
