### ISSUE TITLE
Problem to connect the board with your own computer

### ISSUE THREAD

**Issue by jilu7883** [correll/advancedrobotics#54]
we tried to connect our computer to the board, and there is an error show's that "no hostkey alg".
That error can be fixed by made new rsa and dsa keys on the board and it went OK:

~# ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key
~# ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key

but we don't know what's passphrase is? did anyone know?

**Comment by correll** [comment]
Anything that you want I think

**Comment by jilu7883** [comment]
I think we just don't know what passphrase is, we may ask someone else to
find it,thank you.

**Comment by correll** [comment]
Just leave it empty

**Comment by correll** [comment]
It's something you set, not something you need to know

**Comment by jilu7883** [comment]
OK,thank you
