### ISSUE TITLE
Hardware development for Jaguar

### ISSUE THREAD

**Issue by ghost** [correll/advancedrobotics#55]
@Zolkin1(Zach) just noticed that the 80-20's in the Correll lab are slightly more larger than the ones we already cut for the Jaguar. 

Images of the two are as below:

![img_0179](https://cloud.githubusercontent.com/assets/14017199/10712598/c07a518e-7a5b-11e5-808b-31a3f2f0da60.JPG)
![img_0182](https://cloud.githubusercontent.com/assets/14017199/10712597/c075c114-7a5b-11e5-9d08-24726190d0cc.JPG)

I think there is not much difference. We have started cutting the larger 80-20's as those are the only ones that closely resemble the ones already cut for the Jaguar.

**Comment by ghost** [comment]
Also, is there a power-cutting tool in the Correll lab to cut the 80-20's?

**Comment by correll** [comment]
Just hacksaw

**Comment by ghost** [comment]
We are out of angle brackets and appropriate screws. @ryanleonard , @BryanBo-Cao  and I are going to buy the following parts now at McGuckin's.
![img_0194](https://cloud.githubusercontent.com/assets/14017199/10802018/d5cf1598-7d7f-11e5-8f0f-1213fc9158d3.JPG)

To @Zolkin1: Please could you specify if any other parts need to be bought.

**Comment by bryanbocao** [comment]
Have these 80-20 angle brackets and appropriate screws been ordered? Currently are we waiting for them for hardware development?

**Comment by Jorge-C** [comment]
Andy is working on it. He has ordered hardware and will work on it tomorrow I think.

**Comment by correll** [comment]
The hardware is sitting in the CS front office in the 7th floor

On Tue, Nov 10, 2015 at 7:34 PM, Jorge Cañardo Alastuey <
notifications@github.com> wrote:

> Andy is working on it. He has ordered hardware and will work on it
> tomorrow I think.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/correll/advancedrobotics/issues/55#issuecomment-155612677
> .

## 

Assistant Professor
@correlllab, http://correll.cs.colorado.edu
Open robotics textbook: http://amzn.to/1vTjnt9 (buy), http://bit.ly/1vr7ptA
(contribute)

**Comment by Jorge-C** [comment]
It's already in the lab, between our desks.

2015-11-10 17:36 GMT-07:00 Nikolaus Correll notifications@github.com:

> The hardware is sitting in the CS front office in the 7th floor
> 
> On Tue, Nov 10, 2015 at 7:34 PM, Jorge Cañardo Alastuey <

**Comment by bryanbocao** [comment]
Andy, @Jorge-C and I worked on the 80/20 hardware development based on their design:

![img_20151111_152208_hdr](https://cloud.githubusercontent.com/assets/14010288/11111492/e8ffb6ca-88c6-11e5-90ae-024cb9c72e45.jpg)
