### ISSUE TITLE
Run motor driver and IMU simultaneously

### ISSUE THREAD

**Issue by bryanbocao** [correll/advancedrobotics#57]
Motor driver and IMU are connect to Jetson board via the same FTDI. We attempted to run motor driver and receive IMU data simultaneously but failed. The baud rate of motor drive is 115200 baud while IMU's baud rate is 57600 baud.
<img width="512" alt="screen shot 2015-10-28 at 5 22 10 pm" src="https://cloud.githubusercontent.com/assets/14010288/10806132/92226016-7d98-11e5-9319-3069c7dee3d5.png">

---

One of the solutions could be to change motor driver's or IMU's baud rate to the same rate, such that, however, I suspect we might need to add a module for management of these data since they use the same baud rate via the same FTDI.

The other simple solution would be just to buy another FTDI: https://www.sparkfun.com/products/9873, so that motor driver and IMU can be connected to Jetson separately. Branden and I would suggest this solution.

Thank @Branden-Romero & @RohitRaje9362 for help!

Anyone has better ideas?

**Comment by correll** [comment]
We have a ton of FTDI cables in the lab and I gave already some to somebody
a while back.

On Wed, Oct 28, 2015 at 5:31 PM, BryanBo-Cao notifications@github.com
wrote:

> Motor driver and IMU are connect to Jetson board via the same FTDI. We
> attempted to run motor driver and receive IMU data simultaneously but
> failed. The baud rate of motor drive is 115200 baud while IMU's baud rate
> is 57600 baud.
> [image: screen shot 2015-10-28 at 5 22 10 pm]
> 
> ## https://cloud.githubusercontent.com/assets/14010288/10806132/92226016-7d98-11e5-9319-3069c7dee3d5.png
> 
> One of the solutions could be to change motor driver's or IMU's baud rate
> to the same rate, such that, however, I suspect we might need to add a
> module for management of these data since they use the same baud rate via
> the same FTDI.
> 
> The other simple solution would be just to buy another FTDI:
> https://www.sparkfun.com/products/9873, so that motor driver and IMU can
> be connected to Jetson separately. Branden and I would suggest this
> solution.
> 
> Thank @Branden-Romero https://github.com/Branden-Romero & @RohitRaje9362
> https://github.com/RohitRaje9362 for help!
> 
> Anyone has better ideas?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/correll/advancedrobotics/issues/57.

## 

Assistant Professor
@correlllab, http://correll.cs.colorado.edu
Open robotics textbook: http://amzn.to/1vTjnt9 (buy), http://bit.ly/1vr7ptA
(contribute)

**Comment by rmaheshkumarblr** [comment]
Why are we using the same FTDI?  2 weeks back I set a separate FTDI for the
motor and the IMU.. Did we change something?

**Comment by rmaheshkumarblr** [comment]
Re-attached the FTDI we were using earlier and it works fine now.
