### ISSUE TITLE
Mount Jetson on Jaguar

### ISSUE THREAD

**Issue by bryanbocao** [correll/advancedrobotics#59]
<img width="346" alt="screen shot 2015-10-29 at 3 42 06 am" src="https://cloud.githubusercontent.com/assets/14010288/10815041/2a511002-7def-11e5-9409-51fec9eda296.png">

<img width="821" alt="screen shot 2015-10-29 at 3 43 36 am" src="https://cloud.githubusercontent.com/assets/14010288/10815069/4db90f9a-7def-11e5-8fb9-832d3cb53ed7.png">

![img_20151029_030344](https://cloud.githubusercontent.com/assets/14010288/10815113/8d78177a-7def-11e5-9428-da9e6e0f9abe.jpg)

Thank @RohitRaje9362 for help!

Now Jetson could be powered on by the battery again.

@Branden-Romero I think now you could move it around by joystick to measure odometry without worrying about the FTDI cable drawning into the gears...

**Comment by bryanbocao** [comment]
Share the videos from last week:
[Robot moving outside the lab VID 20151029 142200 ](https://youtu.be/bMI5y4v7eDU)
[Robot moving on stones and grass with lego figure VID 20151029 170844 ](https://youtu.be/d7ZqrxK_nzg)
[Robot moving with a human and lego figures VID 20151029 173740](https://youtu.be/lBaOTfgMe3Q)

**Comment by ghost** [comment]
Video of Jaguar climbing stairs successfully:
https://www.youtube.com/watch?v=ajecEemVHm4
