### ISSUE TITLE
Stewart platform: IMU mounting

### ISSUE THREAD

**Issue by Jorge-C** [correll/advancedrobotics#60]
The razor is currently on the top platform with masking tape, but it needs a more permanent solution. Maybe something with screws like the ones used to mount the Jaguar IMU on the metal. Ideally it'd be mounted so that the frame its ROS node returns matches what we need (x pointing towards 1,2, y pointing left, and z up (right handed)), but if not we need to add a tf node to transform coordinates.

**Comment by bryanbocao** [comment]
<img width="628" alt="screen shot 2015-11-06 at 6 48 44 pm" src="https://cloud.githubusercontent.com/assets/14010288/11012825/cd13ab1e-84b7-11e5-85d4-90ccdbceb6a7.png">
![img_20151106_182107](https://cloud.githubusercontent.com/assets/14010288/11012762/7e38df9c-84b6-11e5-8a3b-b0d051f029f5.jpg)
![img_20151106_183105_hdr](https://cloud.githubusercontent.com/assets/14010288/11012764/7e3b7194-84b6-11e5-9bc5-896b5d9ba604.jpg)
![img_20151106_183255_hdr](https://cloud.githubusercontent.com/assets/14010288/11012763/7e3b0f2e-84b6-11e5-80b8-00359b06bbcc.jpg)

Thank @Jorge-C for help!
