### ISSUE TITLE
Stewart platform: control

### ISSUE THREAD

**Issue by Jorge-C** [correll/advancedrobotics#61]
The platform doesn't track pose commands very well (it has too much stationary error, probably because some measurements aren't that great), so we need to stabilize it.

Given that we have an inverse model, we can use feedforward control, but that still has stationary error -> we need to add feedback. This is the type of architecture: http://computationalnonlinear.asmedigitalcollection.asme.org/data/journals/jcnddm/927599/m_cnd_009_01_011014_f001.png

Anybody with interest or experience in controls, feel free to pitch in with suggestions :)

**Comment by correll** [comment]
Is this about the pose after taking IMU inputs into account? The servos should be pretty precise.

**Comment by Jorge-C** [comment]
Some extra PID tuning would be nice to have, but this is working now.

**Comment by correll** [comment]
This is a simple method to get good pid values

https://en.m.wikipedia.org/wiki/Ziegler–Nichols_method
