### ISSUE TITLE
Displaying the GPS Latitude and Longitude on a browser / google maps.

### ISSUE THREAD

**Issue by rmaheshkumarblr** [correll/advancedrobotics#64]

**Comment by rmaheshkumarblr** [comment]
![image](https://cloud.githubusercontent.com/assets/1996917/10925015/f722284e-8247-11e5-80a0-afa458b1e079.png)

Process to get it working on your laptop:

1) Connect to jaguar_ap 
2) SSH to 192.168.205.1 ( IP address of Jaguar )
3) Start roscore
4) Start the GPS launch file or all the services including the GPS
5) Start the rosbridge service `roslaunch rosbridge_server rosbridge_websocket.launch`
6) Make sure you have internet connectivity on your laptop
7) export ROS_IP="IP you were assigned by the jaguar AP"
8) export ROS_MASTER_URI=http://192.168.205.1:11311
9) Open the html file that is uploaded to the code repository.

**Comment by correll** [comment]
Great!

On Tue, Nov 3, 2015 at 4:35 PM, Mahesh Kumar Ravindranathan <
notifications@github.com> wrote:

> [image: image]
> https://cloud.githubusercontent.com/assets/1996917/10925015/f722284e-8247-11e5-80a0-afa458b1e079.png
> 
> Process to get it working on your laptop:
> 
> 1) Connect to jaguar_ap
> 2) SSH to 192.168.205.1 ( IP address of Jaguar )
> 3) Start roscore
> 4) Start the GPS launch file or all the services including the GPS
> 5) Start the rosbridge service roslaunch rosbridge_server
> rosbridge_websocket.launch
> 6) Make sure you have internet connectivity on your laptop
> 7) export ROS_IP="IP you were assigned by the jaguar AP"
> 8) export ROS_MASTER_URI=http://192.168.205.1:11311
> 9) Open the html file that is uploaded to the code repository.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/correll/advancedrobotics/issues/64#issuecomment-153524369
> .

## 

Assistant Professor
@correlllab, http://correll.cs.colorado.edu
Open robotics textbook: http://amzn.to/1vTjnt9 (buy), http://bit.ly/1vr7ptA
(contribute)

**Comment by ikemole** [comment]
@rmaheshkumarblr I've incorporated this into a single page with the camera feed.
