### ISSUE TITLE
Connection to jaguar_ap frequently disconnects

### ISSUE THREAD

**Issue by ikemole** [correll/advancedrobotics#66]
When logged into the Tegra's network (jaguar_ap) through SSH, I lose connection very often and have to reconnect. Sometimes even when sitting next to it, the jaguar_ap wireless signal strength is still about 40% or less. 

Does anyone know how to make it have a more reliable and stable connection?

**Comment by rmaheshkumarblr** [comment]
The PCIe Card has option to have 2 antennas. Fixing another antenna may fix the issue. The other option is to use a USB wireless adapter which can be attached outside the Jaguar which will give better signal. I think we are in the process of getting one of those already.
