### ISSUE TITLE
Mount Occam60 on Jaguar

### ISSUE THREAD

**Issue by correll** [correll/advancedrobotics#7]
Make sure does not interfere with Stewart platform

**Comment by Zolkin1** [comment]
If anyone gets a chance/way to make these parts, attached are the Occam60 mounting parts. The second one I was planning on 3d printing. And then we need a 12 in piece that will vertically mount to the occam. Also I will not be able to come in this week.
![80-20 20mm support strut](https://cloud.githubusercontent.com/assets/13017206/10773924/d11f20b8-7cc3-11e5-8fea-40e92c0bf0c7.jpg)
![fab occam 60 mount](https://cloud.githubusercontent.com/assets/13017206/10773969/0dd713d0-7cc4-11e5-98ac-ec1c905e22c7.jpg)
