### ISSUE TITLE
Liquid delivery

### ISSUE THREAD

**Issue by Jorge-C** [correll/advancedrobotics#70]
Delivering coffee using the Stewart platform would be cool, but look at this tank: https://i.imgur.com/JdIqPUP.gifv

**Comment by correll** [comment]
$80k worth of IMU doing its job right there

On Fri, Nov 20, 2015 at 4:45 PM, Jorge Cañardo Alastuey <
notifications@github.com> wrote:

> Delivering coffee using the Stewart platform would be cool, but look at
> this tank: https://i.imgur.com/JdIqPUP.gifv
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/correll/advancedrobotics/issues/70.

## 

Assistant Professor
@correlllab, http://correll.cs.colorado.edu
Open robotics textbook: http://amzn.to/1vTjnt9 (buy), http://bit.ly/1vr7ptA
(contribute)
