### ISSUE TITLE
Integrate all hardware components

### ISSUE THREAD

**Issue by bryanbocao** [correll/advancedrobotics#71]

**Comment by bryanbocao** [comment]
![jaguar1](https://cloud.githubusercontent.com/assets/14010288/11331959/819f38aa-917e-11e5-89ef-25b3bc5aef08.jpg)

![jaguar3](https://cloud.githubusercontent.com/assets/14010288/11341427/a8358ba4-91bf-11e5-9b6d-c509aeb1aa31.jpg)

![jaguar2](https://cloud.githubusercontent.com/assets/14010288/11331990/ba3e6258-917e-11e5-9b3b-796fa830b5bd.jpg)

However, we still need to unmount stewart platfom to charge the battery unitl #56 (Embedded Battery Management System for the Jaguar) is solved.

So far I have focused on hardware for weeks, I will concentrate more on web-map in the future.

**Comment by correll** [comment]
This beast looks awesome!
