### ISSUE TITLE
Turn on Jetson automatically when turning on Jaguar from battery

### ISSUE THREAD

**Issue by bryanbocao** [correll/advancedrobotics#72]
Currently we have to turn on the power by the button on the back of Jaguar, and then press the power button of Jetson inside Jaguar, which is extremely inconvenient.

**Comment by ghost** [comment]
I suppose the Jetson will turn on automatically as long as it's reset
capacitors stay charged i.e. as long as the battery is always connected and
the Jetson is not explicitly shut down.

However, after removing the batteries for charging, restarting the Jetson
does become an inconvenience.

Rohit

**Comment by mcguire-steve** [comment]
The small button on the front panel next to the main power switch is wired
to a header for just such a reason. The LED inside and the button connect
to the 'front panel' header block on the Jetson.
-Steve

**Comment by correll** [comment]
Maybe it's possible to bridge the power button?

**Comment by Jorge-C** [comment]
The small button works.
