### ISSUE TITLE
Need new usb to serial breakout for motor board

### ISSUE THREAD

**Issue by Branden-Romero** [correll/advancedrobotics#77]
https://www.sparkfun.com/products/12731

**Comment by correll** [comment]
John Klingner has some, they should be on the workbench in one of the
left-side drawers (labeled "FTDI cables"). There are 3.3V and 5V cables.

On Tue, Dec 8, 2015 at 5:09 PM, Branden Romero notifications@github.com
wrote:

> https://www.sparkfun.com/products/12731
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/correll/advancedrobotics/issues/77.

## 

Assistant Professor
@correlllab, http://correll.cs.colorado.edu
Open robotics textbook: http://amzn.to/1vTjnt9 (buy), http://bit.ly/1vr7ptA
(contribute)
