### ISSUE TITLE
Testing the Color Camera

### ISSUE THREAD

**Issue by ikemole** [correll/advancedrobotics#78]
I tested the color camera that was brought in yesterday and the image was very dark:

![color_occam](https://cloud.githubusercontent.com/assets/2020624/11749560/b62e1c1e-9feb-11e5-8f3a-f7870b71d5f3.png)

**Comment by bryanbocao** [comment]
Use the Occam Indigo software downloaded from http://occamvisiongroup.com/knowledgebase/windows-drivers-and-tools/ on Windows and set the "Gain" to Auto and save this configuration would solve this issue:

![qq 20151217171112](https://cloud.githubusercontent.com/assets/14010288/11885924/59702102-a4e1-11e5-96cc-784408496ac2.png)

![qq 20151217171158](https://cloud.githubusercontent.com/assets/14010288/11885925/597c312c-a4e1-11e5-8761-842efaddfae5.png)

Thank @rmaheshkumarblr for help!
