### ISSUE TITLE
Create order app prototype for video

### ISSUE THREAD

**Issue by bryanbocao** [correll/advancedrobotics#79]
#76

Hey guys since I have not upgraded my Apple Account to App Developer, I just used what I have to creat a website http://bryanbo-cao.me to order coffee temporally (only for filming). If I have more time I would like to develop an app or a robust website for ordering.

For filming, use your phone to open this address: http://bryanbo-cao.me on Chrome, scroll down, the tab bar and address field should disappear and it would look like an app like the pictures shown below:

<img width="348" alt="screen shot 2015-12-17 at 12 12 34 am" src="https://cloud.githubusercontent.com/assets/14010288/11863667/eaff43da-a452-11e5-83a5-a763b9c90cea.png">

<img width="339" alt="screen shot 2015-12-17 at 12 00 00 am" src="https://cloud.githubusercontent.com/assets/14010288/11863636/ac0b6e88-a452-11e5-8f04-374567b45f81.png">

<img width="335" alt="screen shot 2015-12-17 at 12 19 56 am" src="https://cloud.githubusercontent.com/assets/14010288/11863771/07cd406a-a454-11e5-97d8-5cb9517d27d2.png">

<img width="335" alt="screen shot 2015-12-17 at 12 21 26 am" src="https://cloud.githubusercontent.com/assets/14010288/11863783/283cd28e-a454-11e5-8e85-0e76cdcdf5a2.png">

BTW on Thursday I would like to help to recover Jaguar.

**Comment by correll** [comment]
Great!

On Thu, Dec 17, 2015 at 12:16 AM, BryanBo-Cao notifications@github.com
wrote:

> #76 https://github.com/correll/advancedrobotics/issues/76
> Hey guys since I have not upgraded my Apple Account to App Developer, I
> just used what I have to creat a website http://bryanbo-cao.me to order
> coffee temporally (only for filming). If I have more time I would like to
> develop an app or a robust website for ordering.
> 
> For filming, use your phone to open this address: http://bryanbo-cao.me
> on Chrome, scroll down, the tab bar and address field should disappear and
> it would look like an app like the pictures shown below:
> 
> [image: screen shot 2015-12-17 at 12 12 34 am]
> https://cloud.githubusercontent.com/assets/14010288/11863667/eaff43da-a452-11e5-83a5-a763b9c90cea.png
> 
> [image: screen shot 2015-12-17 at 12 00 00 am]
> https://cloud.githubusercontent.com/assets/14010288/11863636/ac0b6e88-a452-11e5-8f04-374567b45f81.png
> 
> [image: screen shot 2015-12-17 at 12 00 29 am]
> https://cloud.githubusercontent.com/assets/14010288/11863674/fe45a042-a452-11e5-8b86-fe8d6490829e.png
> 
> [image: screen shot 2015-12-17 at 12 00 37 am]
> https://cloud.githubusercontent.com/assets/14010288/11863678/09e13e0c-a453-11e5-9edc-3fb70b3039f0.png
> 
> BTW on Thursday I would like to help to recover Jaguar.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/correll/advancedrobotics/issues/79.

## 

Assistant Professor
@correlllab, http://correll.cs.colorado.edu
Open robotics textbook: http://amzn.to/1vTjnt9 (buy), http://bit.ly/1vr7ptA
(contribute)
