### ISSUE TITLE
Install RTABMAP

### ISSUE THREAD

**Issue by correll** [correll/advancedrobotics#9]

**Comment by ghost** [comment]
I will be installing RTABMAP on Tuesday. If ROS and OpenCV are installed on early Monday, I will be doing it that day itself. Do join me if you are free then?

Rohit

**Comment by ryanleonard** [comment]
I'll be there Tuesday!Ryan

Sent from Outlook

On Sun, Aug 30, 2015 at 8:52 AM -0700, "Rohit Narendra Raje" notifications@github.com wrote:
I will be installing RTABMAP on Tuesday. If ROS and OpenCV are installed on early Monday, I will be doing it that day itself. Do join me if you are free then?

Rohit

---

**Comment by mira67** [comment]
I will try to be there 1130 Monday, and maybe we can install the omni 60
driver also.

Qi

On Sun, Aug 30, 2015 at 9:52 AM, Rohit Narendra Raje <
notifications@github.com> wrote:

> I will be installing RTABMAP on Tuesday. If ROS and OpenCV are installed
> on early Monday, I will be doing it that day itself. Do join me if you are
> free then?
> 
> Rohit
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/correll/advancedrobotics/issues/9#issuecomment-136155411
> .

## 

PhD Candidate
ECEE Department
University of Colorado at Boulder

**Comment by jilu7883** [comment]
I can join in Tuesday, when you guys will meet?

**Comment by ryanleonard** [comment]
Any time before 2 for me
Ryan

Sent from Outlook

On Mon, Aug 31, 2015 at 3:25 PM -0700, "jilu7883" notifications@github.com wrote:
I can join in Tuesday, when you guys will meet?

---

**Comment by jilu7883** [comment]
I can be here around 10:15 tomorrow, maybe early

**Comment by ghost** [comment]
I will be there in the Lab on Tuesday after 1pm. So, you guys can go ahead if you arrive early. BTW, today (Monday), we finished flashing the Jettson (16GiB filesystem) and installed ROS indigo on it. We tried getting the PCIe wifi adapter to function but seems as if the necessary drivers are missing.

**Comment by correll** [comment]
The PCIe will probably require the grinch kernel.

https://devtalk.nvidia.com/default/topic/823132/-customkernel-the-grinch-21-3-4-for-jetson-tk1-developed/

Do you have such a wireless card to play with?

**Comment by ghost** [comment]
There were two PCIe wireless cards already there in the Lab. Found by
Steve! One was from RTL(RealTek) and the other was Intel Centrino
Wireless-N 2230.

**Comment by correll** [comment]
I couldn't actually get this to work previously. I could see the interface and wireless networks, but it would not connect. Maybe one needs to hook up the antenna.

**Comment by rmaheshkumarblr** [comment]
We could get the realtek one working installing the drivers but the problem was that the system hanged after a certain amount of time because of some issue. In the error messages we could see something mentioned about wpa_supplicant.

**Comment by correll** [comment]
Can you post the whole error message? Maybe someone can figure it out.

**Comment by ghost** [comment]
Installed the grinch kernel. Will check the RTL PCIe again tomorrow!
